window.TURTLE_SPECIES = [
  { code: "ABQ", name: "安布闭壳龟", letter: "A", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Cuora%20amboinensis.jpg" },
  { code: "ALG", name: "阿拉巴马地图龟", letter: "A", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Graptemys%20pulchra.jpg" },
  { code: "ALD", name: "阿尔达布拉象龟", letter: "A", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Aldabrachelys%20gigantea.jpg" },
  { code: "ANG", name: "安南龟", letter: "A", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mauremys%20annamensis.jpg" },
  { code: "AOS", name: "澳洲蛇颈龟", letter: "A", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chelodina%20longicollis.jpg" },
  { code: "ATG", name: "阿根廷侧颈龟", letter: "A", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Phrynops%20hilarii.jpg" },
  { code: "AXG", name: "阿拉莫泥龟", letter: "A", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kinosternon%20alamosae.jpg" },

  { code: "BAG", name: "北美拟地图龟", letter: "B", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Graptemys%20pseudogeographica.jpg" },
  { code: "BCG", name: "白唇蛋龟", letter: "B", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kinosternon%20leucostomum.jpg" },
  { code: "BDL", name: "北部钻纹龟", letter: "B", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Malaclemys%20terrapin%20terrapin.jpg" },
  { code: "BHN", name: "白喉泥龟", letter: "B", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kinosternon%20leucostomum.jpg" },
  { code: "BJN", name: "扁背麝香龟", letter: "B", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Sternotherus%20depressus.jpg" },
  { code: "BLS", name: "巴西红耳龟", letter: "B", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Trachemys%20scripta%20elegans.jpg" },
  { code: "BMG", name: "斑点箱龟", letter: "B", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Terrapene%20nelsoni.jpg" },
  { code: "BWG", name: "豹纹陆龟", letter: "B", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Stigmochelys%20pardalis.jpg" },
  { code: "BWN", name: "斑纹泥龟", letter: "B", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kinosternon%20baurii.jpg" },

  { code: "CBQ", name: "齿缘闭壳龟", letter: "C", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Cuora%20flavomarginata.jpg" },
  { code: "CBT", name: "刺鳖", letter: "C", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Apalone%20spinifera.jpg" },
  { code: "CEG", name: "长颈龟", letter: "C", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chelodina%20longicollis.jpg" },
  { code: "CGI", name: "草龟", letter: "C", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mauremys%20reevesii.jpg" },
  { code: "CHG", name: "巢湖龟", letter: "C", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mauremys%20reevesii.jpg" },
  { code: "CJD", name: "长颈巨龟", letter: "C", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chelodina%20expansa.jpg" },
  { code: "CJT", name: "赤颈龟", letter: "C", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Emydura%20subglobosa.jpg" },
  { code: "CSG", name: "刺山龟", letter: "C", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Heosemys%20spinosa.jpg" },
  { code: "CUG", name: "粗颈龟", letter: "C", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Siebenrockiella%20crassicollis.jpg" },

  { code: "DBG", name: "地龟", letter: "D", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Geoemyda%20spengleri.jpg" },
  { code: "DDG", name: "东部箱龟", letter: "D", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Terrapene%20carolina%20carolina.jpg" },
  { code: "DHG", name: "玳瑁", letter: "D", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Eretmochelys%20imbricata.jpg" },
  { code: "DJG", name: "东部锦龟", letter: "D", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chrysemys%20picta%20picta.jpg" },
  { code: "DNG", name: "东部泥龟", letter: "D", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kinosternon%20subrubrum.jpg" },
  { code: "DTG", name: "地图龟", letter: "D", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Graptemys%20geographica.jpg" },
  { code: "DUG", name: "大鳄龟", letter: "D", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Macrochelys%20temminckii.jpg" },

  { code: "EBQ", name: "额带闭壳龟", letter: "E", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Cuora%20galbinifrons.jpg" },
  { code: "EJG", name: "欧洲泽龟", letter: "E", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Emys%20orbicularis.jpg" },
  { code: "EMG", name: "欧洲池龟", letter: "E", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Emys%20orbicularis.jpg" },

  { code: "FBT", name: "佛州软壳龟", letter: "F", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Apalone%20ferox.jpg" },
  { code: "FHD", name: "佛州红肚龟", letter: "F", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Pseudemys%20nelsoni.jpg" },
  { code: "FZG", name: "佛州箱龟", letter: "F", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Terrapene%20carolina%20bauri.jpg" },

  { code: "GBG", name: "哥伦比亚红腿陆龟", letter: "G", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chelonoidis%20carbonarius.jpg" },
  { code: "GDT", name: "古巴彩龟", letter: "G", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Trachemys%20decussata.jpg" },
  { code: "GHG", name: "果核蛋龟", letter: "G", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Sternotherus%20odoratus.jpg" },
  { code: "GJG", name: "高加索陆龟", letter: "G", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Testudo%20graeca.jpg" },
  { code: "GLD", name: "哥法地鼠龟", letter: "G", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Gopherus%20polyphemus.jpg" },
  { code: "GNG", name: "哥伦比亚木纹龟", letter: "G", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Rhinoclemmys%20melanosterna.jpg" },

  { code: "HBQ", name: "黑颈闭壳龟", letter: "H", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Cuora%20yunnanensis.jpg" },
  { code: "HDG", name: "红肚短颈龟", letter: "H", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Emydura%20subglobosa.jpg" },
  { code: "HED", name: "红耳龟", letter: "H", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Trachemys%20scripta%20elegans.jpg" },
  { code: "HET", name: "黄额闭壳龟", letter: "H", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Cuora%20galbinifrons.jpg" },
  { code: "HGG", name: "黑腹刺颈龟", letter: "H", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Acanthochelys%20spixii.jpg" },
  { code: "HHG", name: "黄喉拟水龟", letter: "H", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mauremys%20mutica.jpg" },
  { code: "HJG", name: "黑颈乌龟", letter: "H", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mauremys%20nigricans.jpg" },
  { code: "HNT", name: "红腿陆龟", letter: "H", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chelonoidis%20carbonarius.jpg" },
  { code: "HSG", name: "黄头庙龟", letter: "H", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Heosemys%20annandalii.jpg" },
  { code: "HYG", name: "黄缘闭壳龟", letter: "H", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Cuora%20flavomarginata.jpg" },
  { code: "HZG", name: "黄泽龟", letter: "H", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mauremys%20mutica.jpg" },

  { code: "JBG", name: "加勒比彩龟", letter: "J", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Trachemys%20decussata.jpg" },
  { code: "JBT", name: "锦箱龟", letter: "J", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Terrapene%20ornata.jpg" },
  { code: "JDG", name: "几何陆龟", letter: "J", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Psammobates%20geometricus.jpg" },
  { code: "JQG", name: "金钱龟", letter: "J", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Cuora%20trifasciata.jpg" },
  { code: "JTG", name: "锯缘摄龟", letter: "J", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Cyclemys%20dentata.jpg" },
  { code: "JWG", name: "锦龟", letter: "J", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chrysemys%20picta.jpg" },
  { code: "JYG", name: "锯齿龟", letter: "J", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Cyclemys%20dentata.jpg" },

  { code: "KBT", name: "肯氏丽龟", letter: "K", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Lepidochelys%20kempii.jpg" },
  { code: "KJG", name: "盔头龟", letter: "K", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Pelomedusa%20subrufa.jpg" },
  { code: "KNG", name: "枯叶龟", letter: "K", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chelus%20fimbriata.jpg" },
  { code: "KSG", name: "卡罗莱纳箱龟", letter: "K", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Terrapene%20carolina.jpg" },

  { code: "LBG", name: "剌背麝香龟", letter: "L", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Sternotherus%20carinatus.jpg" },
  { code: "LHG", name: "丽龟", letter: "L", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Lepidochelys%20olivacea.jpg" },
  { code: "LJG", name: "棱皮龟", letter: "L", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Dermochelys%20coriacea.jpg" },
  { code: "LKG", name: "绿海龟", letter: "L", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chelonia%20mydas.jpg" },
  { code: "LNG", name: "绿拟水龟", letter: "L", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mauremys%20mutica.jpg" },
  { code: "LSG", name: "绿毛龟", letter: "L", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mauremys%20reevesii.jpg" },
  { code: "LWG", name: "丽纹龙龟", letter: "L", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Rhinoclemmys%20pulcherrima.jpg" },

  { code: "MBG", name: "马来闭壳龟", letter: "M", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Cuora%20amboinensis.jpg" },
  { code: "MDG", name: "马来巨龟", letter: "M", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Orlitia%20borneensis.jpg" },
  { code: "MHG", name: "密西西比地图龟", letter: "M", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Graptemys%20pseudogeographica%20kohnii.jpg" },
  { code: "MJG", name: "缅甸星龟", letter: "M", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Geochelone%20platynota.jpg" },
  { code: "MLG", name: "缅甸陆龟", letter: "M", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Indotestudo%20elongata.jpg" },
  { code: "MNG", name: "缅甸孔雀龟", letter: "M", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Morenia%20ocellata.jpg" },
  { code: "MRT", name: "玛塔龟", letter: "M", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chelus%20fimbriata.jpg" },
  { code: "MSG", name: "麝香龟", letter: "M", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Sternotherus%20odoratus.jpg" },
  { code: "MUG", name: "木雕水龟", letter: "M", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Glyptemys%20insculpta.jpg" },

  { code: "NBG", name: "南部锦龟", letter: "N", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chrysemys%20picta%20dorsalis.jpg" },
  { code: "NMG", name: "南美木纹龟", letter: "N", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Rhinoclemmys%20punctularia.jpg" },
  { code: "NNG", name: "南美侧颈龟", letter: "N", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Podocnemis%20expansa.jpg" },
  { code: "NTG", name: "拟鳄龟", letter: "N", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chelydra%20serpentina.jpg" },

  { code: "PBG", name: "平背麝香龟", letter: "P", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Sternotherus%20depressus.jpg" },
  { code: "PDG", name: "潘氏闭壳龟", letter: "P", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Cuora%20pani.jpg" },
  { code: "PGG", name: "平背海龟", letter: "P", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Natator%20depressus.jpg" },
  { code: "PHG", name: "平胸龟", letter: "P", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Platysternon%20megacephalum.jpg" },
  { code: "PMG", name: "普通麝香龟", letter: "P", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Sternotherus%20odoratus.jpg" },
  { code: "PTG", name: "猪鼻龟", letter: "P", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Carettochelys%20insculpta.jpg" },

  { code: "QBT", name: "前棱闭壳龟", letter: "Q", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Cuora%20mouhotii.jpg" },
  { code: "QJG", name: "牟氏水龟", letter: "Q", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Glyptemys%20muhlenbergii.jpg" },
  { code: "QYG", name: "翘缘陆龟", letter: "Q", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Testudo%20marginata.jpg" },

  { code: "RBG", name: "日本石龟", letter: "R", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mauremys%20japonica.jpg" },
  { code: "RLG", name: "日本地龟", letter: "R", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Geoemyda%20japonica.jpg" },
  { code: "RMT", name: "日本木纹龟", letter: "R", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mauremys%20japonica.jpg" },
  { code: "RTG", name: "辐射陆龟", letter: "R", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Astrochelys%20radiata.jpg" },

  { code: "SBQ", name: "三线闭壳龟", letter: "S", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Cuora%20trifasciata.jpg" },
  { code: "SDG", name: "苏卡达陆龟", letter: "S", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Centrochelys%20sulcata.jpg" },
  { code: "SGG", name: "四眼斑龟", letter: "S", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Sacalia%20quadriocellata.jpg" },
  { code: "SHG", name: "山瑞鳖", letter: "S", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Palea%20steindachneri.jpg" },
  { code: "SLG", name: "苏拉威西森林龟", letter: "S", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Leucocephalon%20yuwonoi.jpg" },
  { code: "SNG", name: "三趾箱龟", letter: "S", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Terrapene%20carolina%20triunguis.jpg" },
  { code: "SPG", name: "蛇鳄龟", letter: "S", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chelydra%20serpentina.jpg" },
  { code: "SSG", name: "四爪陆龟", letter: "S", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Testudo%20horsfieldii.jpg" },
  { code: "STG", name: "射纹龟", letter: "S", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Astrochelys%20radiata.jpg" },

  { code: "TBG", name: "头盔龟", letter: "T", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Pelomedusa%20subrufa.jpg" },
  { code: "TDG", name: "台湾草龟", letter: "T", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mauremys%20reevesii.jpg" },
  { code: "TGG", name: "突背地图龟", letter: "T", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Graptemys%20nigrinoda.jpg" },
  { code: "THG", name: "条颈摄龟", letter: "T", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Cyclemys%20oldhamii.jpg" },
  { code: "TMG", name: "剃刀麝香龟", letter: "T", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Sternotherus%20carinatus.jpg" },
  { code: "TNG", name: "条纹泥龟", letter: "T", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kinosternon%20baurii.jpg" },
  { code: "TYG", name: "泰国食螺龟", letter: "T", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Malayemys%20subtrijuga.jpg" },

  { code: "WBG", name: "瓦哈卡泥龟", letter: "W", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kinosternon%20oaxacae.jpg" },
  { code: "WJG", name: "西部锦龟", letter: "W", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chrysemys%20picta%20bellii.jpg" },
  { code: "WNG", name: "屋顶龟", letter: "W", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Pangshura%20tecta.jpg" },
  { code: "WTG", name: "乌龟", letter: "W", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mauremys%20reevesii.jpg" },

  { code: "XBG", name: "西部箱龟", letter: "X", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Terrapene%20ornata.jpg" },
  { code: "XDT", name: "星点水龟", letter: "X", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Clemmys%20guttata.jpg" },
  { code: "XEG", name: "小鳄龟", letter: "X", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chelydra%20serpentina.jpg" },
  { code: "XFD", name: "西非侧颈龟", letter: "X", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Pelusios%20castaneus.jpg" },
  { code: "XGG", name: "希腊陆龟", letter: "X", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Testudo%20graeca.jpg" },
  { code: "XNG", name: "西部彩龟", letter: "X", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chrysemys%20picta%20bellii.jpg" },
  { code: "XPG", name: "星斑陆龟", letter: "X", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Geochelone%20elegans.jpg" },

  { code: "YBG", name: "印度黑龟", letter: "Y", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Melanochelys%20trijuga.jpg" },
  { code: "YDG", name: "印度棱背龟", letter: "Y", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Pangshura%20tecta.jpg" },
  { code: "YHG", name: "鹰嘴龟", letter: "Y", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Platysternon%20megacephalum.jpg" },
  { code: "YLG", name: "亚达伯拉象龟", letter: "Y", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Aldabrachelys%20gigantea.jpg" },
  { code: "YNT", name: "印度星龟", letter: "Y", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Geochelone%20elegans.jpg" },
  { code: "YSG", name: "亚洲巨龟", letter: "Y", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Manouria%20emys.jpg" },
  { code: "YTG", name: "亚洲黄头庙龟", letter: "Y", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Heosemys%20annandalii.jpg" },

  { code: "ZBG", name: "中部锦龟", letter: "Z", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chrysemys%20picta%20marginata.jpg" },
  { code: "ZCG", name: "中华草龟", letter: "Z", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mauremys%20reevesii.jpg" },
  { code: "ZDG", name: "钻纹龟", letter: "Z", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Malaclemys%20terrapin.jpg" },
  { code: "ZHG", name: "中华花龟", letter: "Z", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mauremys%20sinensis.jpg" },
  { code: "ZJG", name: "珍珠龟", letter: "Z", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Mauremys%20sinensis.jpg" },
  { code: "ZMG", name: "中美木纹龟", letter: "Z", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Rhinoclemmys%20pulcherrima.jpg" },
  { code: "ZRG", name: "棕靴陆龟", letter: "Z", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Manouria%20emys.jpg" },
  { code: "ZYG", name: "窄桥蛋龟", letter: "Z", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Claudius%20angustatus.jpg" }
];
